import streamlit as streamlit_app
import pandas as pd
import numpy as np
import pickle
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef, classification_report

streamlit_app.title("Machine Learning Classification Evaluation App")
streamlit_app.write("Upload your test dataset and select a model to view evaluation metrics.")

# a. Dataset upload option (CSV)
uploaded_file = streamlit_app.file_uploader("Upload Test CSV File", type=["csv"])

if uploaded_file is not None:
    # Load test data
    test_data = pd.read_csv(uploaded_file)
    streamlit_app.write("### Test Data Preview", test_data.head())
    
    if 'Target' not in test_data.columns:
        streamlit_app.error("The test dataset must contain a 'Target' column.")
    else:
        X_test = test_data.drop(columns=['Target'])
        y_test = test_data['Target']
        
        # b. Model selection dropdown
        model_options = ["Logistic_Regression", "Decision_Tree", "kNN", "Naive_Bayes", "Random_Forest"]
        selected_model_name = streamlit_app.selectbox("Choose a Model for Evaluation", model_options)
        
        try:
            # Load the pre-trained model file
            with open(f"model/{selected_model_name}.pkl", "rb") as f:
                model = pickle.load(f)
                
            # Predict
            preds = model.predict(X_test)
            
            # Handle probabilities safely for AUC score
            if hasattr(model, "predict_proba"):
                probs = model.predict_proba(X_test)[:, 1]
            else:
                probs = preds
                
            # c. Display of evaluation metrics
            streamlit_app.write(f"## Metrics for {selected_model_name}")
            
            col1, col2, col3 = streamlit_app.columns(3)
            col1.metric("Accuracy", f"{accuracy_score(y_test, preds):.4f}")
            col2.metric("AUC Score", f"{roc_auc_score(y_test, probs):.4f}")
            col3.metric("Precision", f"{precision_score(y_test, preds, zero_division=0):.4f}")
            
            col4, col5, col6 = streamlit_app.columns(3)
            col4.metric("Recall", f"{recall_score(y_test, preds, zero_division=0):.4f}")
            col5.metric("F1 Score", f"{f1_score(y_test, preds, zero_division=0):.4f}")
            col6.metric("MCC Score", f"{matthews_corrcoef(y_test, preds):.4f}")
            
            # d. Classification report
            streamlit_app.write("### Classification Report")
            report = classification_report(y_test, preds, output_dict=False)
            streamlit_app.text(report)
            
        except FileNotFoundError:
            streamlit_app.error(f"Model file model/{selected_model_name}.pkl not found. Make sure to run train_models.py first.")
else:
    streamlit_app.info("Please upload the 'test_data.csv' file generated by the training script to begin.")